[package]
name = "auth0-management"
version = "0.0.4"
authors = ["Marvin Countryman <me@maar.vin>"]
edition = "2018"
description = "An unofficial client for Auth0 Management API."

readme = "./README.md"
license = "MIT"
keywords = ["auth0", "reqwest", "management", "api"]
categories = [
  "api-bindings",
  "asynchronous",
  "authentication"
]
repository = "https://github.com/mcountryman/auth0-management"
documentation = "https://docs.rs/auth0-management"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.10", features = ["json"] }
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
async-mutex = "1.4"

[dev-dependencies]
tokio = { version = "*", features = ["macros"] }
